openapi: 3.0.0
info:
  title: Melodiary API - OpenAPI 3.0
  description: |
    ### 당신의 하루를 음악과 함께 기록하세요.
  contact:
    email: melodiary@gmail.com
  version: 1.0.0
servers:
  - url: https://api.melodiary.site
tags:
  - name: user
    description: 유저 관련 API
  - name: mate
    description: 친구 관련 API
  - name: notification
    description: 알림 관련 API

paths:
  /user/signUp:
    post:
      tags:
        - user
      summary: 회원가입
      description: |
        회원가입 성공한 경우 201 코드와 JWT를 리턴합니다.

        요청 구문이 잘못된 경우 400 코드를 리턴합니다.

        그 이외의 경우 500 코드를 리턴합니다.
      requestBody:
        description: |
          OAuth 서비스 이름

          권한부여코드 (Authorization code)
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpBody'
        required: true
      responses:
        '201':
          description: 회원가입 및 유저 생성 성공
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/AccessToken'
                  - $ref: '#/components/schemas/RefreshToken'
        '500':
          description: 내부 서버 에러
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /user/signIn:
    post:
      tags:
        - user
      summary: 로그인
      description: |
        로그인 성공한 경우 200 코드와 JWT를 리턴합니다.

        요청 구문이 잘못된 경우 400 코드를 리턴합니다.

        가입되지 않은 사용자일 경우 404 코드를 리턴합니다. 이 경우 회원가입을 진행해야 합니다.

        그 이외의 경우 500 코드를 리턴합니다.
      requestBody:
        description: |
          OAuth 서비스 이름

          권한부여코드(Authorization code)
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpBody'
        required: true
      responses:
        '200':
          description: 로그인 성공
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/AccessToken'
                  - $ref: '#/components/schemas/RefreshToken'
        '404':
          description: 해당 유저의 계정이 없음 (회원가입 필요)
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'Cannot find user account'
        '500':
          description: 내부 서버 에러
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /user/tokenReissue:
    post:
      tags:
        - user
      summary: Access token 재발급
      description: |
        Access token 재발급에 성공한 경우 200 코드와 재발급된 access token과 refresh token을 리턴합니다.

        요청 구문이 잘못된 경우 400 코드를 리턴합니다.

        Refresh token이 만료된 경우 401 코드를 리턴합니다. 이 경우 다시 로그인해야 합니다.

        그 이외의 경우 500 코드를 리턴합니다.
      requestBody:
        description: Refresh token
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshToken'
        required: true
      responses:
        '200':
          description: Access token 재발급 성공
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/AccessToken'
                  - $ref: '#/components/schemas/RefreshToken'
        '400':
          description: 잘못된 요청 구문
          content:
            applicaiton/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'Bad request'
        '401':
          description: Refresh token 만료. 재 로그인 해야함
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'The refresh token is expired'

        '500':
          description: 내부 서버 에러
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /user/checkNickname:
    post:
      tags:
        - user
      summary: 닉네임 중복확인
      description: |
        사용 가능한 닉네임일 경우 200 코드를 리턴합니다.

        중복된 닉네임일 경우 400 코드를 리턴합니다.

        그 이외의 경우 500 코드를 리턴합니다.
      requestBody:
        description: 중복 확인할 닉네임
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Nickname'
        required: true
      responses:
        '200':
          description: 닉네임 사용 가능
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'The nickname is valid'
        '400':
          description: 닉네임 사용 불가
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'The nickname is duplicated'
        '500':
          description: 내부 서버 에러
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /user/myInfo:
    get:
      tags:
        - user
      summary: 나의 정보 확인
      description: |
        사용자 정보를 가져오는데 성공한 경우 200 코드와 사용자의 정보를 리턴합니다.

        Access token이 유효하지 않을 경우 401 코드를 리턴합니다. 이 경우 access token을 재발급 받아야 합니다.

        그 이외의 경우 500 코드를 리턴합니다.
      security:
        - BearerAuth: []
      responses:
        '200':
          description: 사용자 정보 가져오기 성공
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
        '401':
          description: Access token이 유효하지 않거나 만료됨
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'The access token is invalid or expired'
        '500':
          description: 내부 서버 에러
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /user/search:
    get:
      tags:
        - user
      summary: 사용자 검색
      description: |
        요청 query string에 검색할 사용자의 닉네임이나 이메일을 담아야합니다.

        사용자 검색에 성공한 경우 200 코드와 검색된 사용자의 정보를 리턴합니다.

        요청 구문이 잘못된 경우 400 코드를 리턴합니다.

        존재하지 않는 사용자일 경우 404 코드를 리턴합니다.

        그 이외의 경우 500 코드를 리턴합니다.
      parameters:
        - $ref: '#/components/parameters/UserNickname'
        - $ref: '#/components/parameters/UserEmail'
      responses:
        '200':
          description: 검색된 사용자 ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MateInfo'
        '400':
          description: 잘못된 요청 구문
          content:
            applicaiton/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'Bad request'
        '404':
          description: 존재하지 않는 사용자
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'Not found such user'
        '500':
          description: 내부 서버 에러
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /user/changeProfileImg:
    put:
      tags:
        - user
      summary: 사용자 프로필 사진 변경
      description: |
        프로필 사진 변경에 성공한 경우 200 코드를 리턴합니다.

        요청의 이미지 URL이 유효하지 않은 경우 400 코드를 리턴합니다.

        Access token이 유효하지 않을 경우 401 코드를 리턴합니다. 이 경우 access token을 재발급 받아야 합니다.

        그 이외의 경우 500 코드를 리턴합니다.
      security:
        - BearerAuth: []
      requestBody:
        description: 변경할 이미지의 URL
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImgURL'
        required: true
      responses:
        '200':
          description: 프로필 이미지 변경 성공
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'Successfully changed the profile image'
        '400':
          description: 유효하지 않은 이미지 URL
          content:
            applicaiton/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'The URL is invalid'
        '401':
          description: Access token이 유효하지 않거나 만료됨
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'The access token is invalid or expired'
        '500':
          description: 내부 서버 에러
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /user/changeBackgroundImg:
    put:
      tags:
        - user
      summary: 마이페이지 배경 사진 변경
      description: |
        마이페이지 배경 사진 변경에 성공한 경우 200 코드를 리턴합니다.

        요청의 이미지 URL이 유효하지 않은 경우 400 코드를 리턴합니다.

        Access token이 유효하지 않을 경우 401 코드를 리턴합니다. 이 경우 access token을 재발급 받아야 합니다.

        그 이외의 경우 500 코드를 리턴합니다.
      security:
        - BearerAuth: []
      requestBody:
        description: 변경할 배경 이미지의 URL
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ImgURL'
        required: true
      responses:
        '200':
          description: 마이페이지 배경 이미지 변경 성공
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'Successfully changed the profile image'
        '400':
          description: 유효하지 않은 이미지 URL
          content:
            applicaiton/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'The URL is invalid'
        '401':
          description: Access token이 유효하지 않거나 만료됨
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'The access token is invalid or expired'
        '500':
          description: 내부 서버 에러
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /user/logout:
    post:
      tags:
        - user
      summary: 사용자 로그아웃
      description: |
        사용자 로그아웃에 성공한 경우 200 코드를 리턴합니다.

        Access token이 유효하지 않을 경우 401 코드를 리턴합니다. 이 경우 access token을 재발급 받아야 합니다.

        그 이외의 경우 500 코드를 리턴합니다.
      security:
        - BearerAuth: []
      responses:
        '200':
          description: 사용자 access token 삭제 및 로그아웃 성공
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'Successfully log out'
        '401':
          description: Access token이 유효하지 않거나 만료됨
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'The access token is invalid or expired'
        '500':
          description: 내부 서버 에러
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /user/deactivate:
    delete:
      tags:
        - user
      summary: 회원 탈퇴
      description: |
        회원 탈퇴 처리가 성공한 경우 200 코드를 리턴합니다.

        Access token이 유효하지 않을 경우 401 코드를 리턴합니다. 이 경우 access token을 재발급 받아야 합니다.

        그 이외의 경우 500 코드를 리턴합니다.
      security:
        - BearerAuth: []
      responses:
        '200':
          description: 회원 탈퇴 처리 및 정보 삭제 성공
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'The user has deleted'
        '401':
          description: Access token이 유효하지 않거나 만료됨
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'The access token is invalid or expired'
        '500':
          description: 내부 서버 에러
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /mate/mates:
    get:
      tags:
        - mate
      summary: 친구 목록 확인
      description: |
        친구 목록을 가져오는데 성공한 경우 200 코드와 친구 목록을 리턴합니다.

        Access token이 유효하지 않을 경우 401 코드를 리턴합니다. 이 경우 access token을 재발급 받아야 합니다.

        친구로 등록된 사용자가 없는 경우 404 코드를 리턴합니다.

        그 이외의 경우 500 코드를 리턴합니다.
      security:
        - BearerAuth: []
      responses:
        '200':
          description: 친구 목록 가져오기 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MateInfo'
        '401':
          description: Access token이 유효하지 않거나 만료됨
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'The access token is invalid or expired'
        '404':
          description: 친구로 등록된 사용자가 없음
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'Not found any mate'
        '500':
          description: 내부 서버 에러
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /mate/receivedRequests:
    get:
      tags:
        - mate
      summary: 받은 친구 요청 목록 확인
      description: |
        받은 친구 요청 목록을 가져오는데 성공한 경우 200 코드와 받은 친구 요청 목록을 리턴합니다.

        Access token이 유효하지 않을 경우 401 코드를 리턴합니다. 이 경우 access token을 재발급 받아야 합니다.

        받은 친구 요청이 없는 경우 404 코드를 리턴합니다.

        그 이외의 경우 500 코드를 리턴합니다.
      security:
        - BearerAuth: []
      responses:
        '200':
          description: 받은 친구 요청 목록 가져오기 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MateInfo'
        '401':
          description: Access token이 유효하지 않거나 만료됨
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'The access token is invalid or expired'
        '404':
          description: 받은 친구 요청이 없음
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'Not found any received request'
        '500':
          description: 내부 서버 에러
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /mate/sentRequests:
    get:
      tags:
        - mate
      summary: 보낸 친구 요청 목록 확인
      description: |
        보낸 친구 요청 목록을 가져오는데 성공한 경우 200 코드와 보낸 친구 요청 목록을 리턴합니다.

        Access token이 유효하지 않을 경우 401 코드를 리턴합니다. 이 경우 access token을 재발급 받아야 합니다.

        보낸 친구 요청이 없는 경우 404 코드를 리턴합니다.

        그 이외의 경우 500 코드를 리턴합니다.
      security:
        - BearerAuth: []
      responses:
        '200':
          description: 보낸 친구 요청 목록 가져오기 성공
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MateInfo'
        '401':
          description: Access token이 유효하지 않거나 만료됨
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'The access token is invalid or expired'
        '404':
          description: 보낸 친구 요청이 없음
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'Not found any sent request'
        '500':
          description: 내부 서버 에러
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /mate/request/{mateID}:
    post:
      tags:
        - mate
      summary: 친구 요청 보내기
      description: |
        요청 path에 친구 요청을 받는 사용자의 ID를 담아야 합니다.

        친구 요청 보내기 성공한 경우 201 코드를 리턴합니다.

        요청 구문이 잘못된 경우 400 코드를 리턴합니다.

        Access token이 유효하지 않을 경우 401 코드를 리턴합니다. 이 경우 access token을 재발급 받아야 합니다.

        그 이외의 경우 500 코드를 리턴합니다.
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/MateID'
      responses:
        '201':
          description: 친구 요청 보내기 성공
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'Successfully sent the mate request'
        '400':
          description: 잘못된 요청 구문
          content:
            applicaiton/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'Bad request'
        '401':
          description: Access token이 유효하지 않거나 만료됨
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'The access token is invalid or expired'
        '500':
          description: 내부 서버 에러
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /mate/accept/{mateID}:
    put:
      tags:
        - mate
      summary: 친구 요청 수락
      description: |
        요청 path에 친구 요청을 보낸 사용자의 ID를 담아야 합니다.

        친구 요청 수락 처리가 성공한 경우 200 코드를 리턴합니다.

        요청 구문이 잘못된 경우 400 코드를 리턴합니다.

        Access token이 유효하지 않을 경우 401 코드를 리턴합니다. 이 경우 access token을 재발급 받아야 합니다.

        그 이외의 경우 500 코드를 리턴합니다.
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/MateID'
      responses:
        '200':
          description: 친구 요청 수락 처리 성공
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'Successfully accepted the mate request'
        '400':
          description: 잘못된 요청 구문
          content:
            applicaiton/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'Bad request'
        '401':
          description: Access token이 유효하지 않거나 만료됨
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'The access token is invalid or expired'
        '500':
          description: 내부 서버 에러
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /mate/reject/{mateID}:
    put:
      tags:
        - mate
      summary: 친구 요청 거절
      description: |
        요청 path에 친구 요청을 보낸 사용자의 ID를 담아야 합니다.

        친구 요청 거절 처리가 성공한 경우 200 코드를 리턴합니다.

        요청 구문이 잘못된 경우 400 코드를 리턴합니다.

        Access token이 유효하지 않을 경우 401 코드를 리턴합니다. 이 경우 access token을 재발급 받아야 합니다.

        그 이외의 경우 500 코드를 리턴합니다.
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/MateID'
      responses:
        '200':
          description: 친구 요청 거절 처리 성공
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'Successfully rejected the mate request'
        '400':
          description: 잘못된 요청 구문
          content:
            applicaiton/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'Bad request'
        '401':
          description: Access token이 유효하지 않거나 만료됨
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'The access token is invalid or expired'
        '500':
          description: 내부 서버 에러
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /mate/unmate/{mateID}:
    delete:
      tags:
        - mate
      summary: 친구 삭제
      description: |
        친구 삭제 처리가 성공한 경우 200 코드를 리턴합니다.

        요청 구문이 잘못된 경우 400 코드를 리턴합니다.

        Access token이 유효하지 않을 경우 401 코드를 리턴합니다. 이 경우 access token을 재발급 받아야 합니다.

        그 이외의 경우 500 코드를 리턴합니다.
      security:
        - BearerAuth: []
      parameters:
        - $ref: '#/components/parameters/MateID'
      responses:
        '200':
          description: 친구 삭제 처리 성공
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'Successfully unmated'
        '400':
          description: 잘못된 요청 구문
          content:
            applicaiton/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'Bad request'
        '401':
          description: Access token이 유효하지 않거나 만료됨
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'The access token is invalid or expired'
        '500':
          description: 내부 서버 에러
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /notification/unread:
    get:
      tags:
        - notification
      summary: 읽지 않은 알림 확인
      description: |
        읽지 않은 알림이 있는 경우 200 코드와 읽지 않은 알림 목록을 리턴합니다.

        Access token이 유효하지 않을 경우 401 코드를 리턴합니다. 이 경우 access token을 재발급 받아야 합니다.

        읽지 않은 알림이 없는 경우 404 코드를 리턴합니다.

        그 이외의 경우 500 코드를 리턴합니다.
      security:
        - BearerAuth: []
      responses:
        '200':
          description: 읽지 않은 알림 목록
          content:
            application/json:
              examples:
                example1:
                  summary: '일기 관련 알림'
                  value:
                    - id: 793
                      content: 'someone commented on your diary'
                      diaryId: 2940
                      category: 'diary'
                      date: '2024-07-26'
                example2:
                  summary: '친구 관련 알림'
                  value:
                    - id: 297
                      content: 'someone wants to be friends with you'
                      category: 'mate'
                      date: '2024-07-26'
        '401':
          description: Access token이 유효하지 않거나 만료됨
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'The access token is invalid or expired'
        '404':
          description: 읽지 않은 알림 없음
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is no unread notification'
        '500':
          description: 내부 서버 에러
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

  /notification/read:
    get:
      tags:
        - notification
      summary: 읽은 알림 기록 확인
      description: |
        읽은 알림이 있는 경우 200 코드와 읽은 알림 목록을 리턴합니다.

        Access token이 유효하지 않을 경우 401 코드를 리턴합니다. 이 경우 access token을 재발급 받아야 합니다.

        읽은 알림이 없는 경우 404 코드를 리턴합니다.

        그 이외의 경우 500 코드를 리턴합니다.
      security:
        - BearerAuth: []
      responses:
        '200':
          description: 읽은 알림 목록
          content:
            application/json:
              examples:
                example1:
                  summary: '일기 관련 알림'
                  value:
                    - id: 793
                      content: 'someone commented on your diary'
                      diaryId: 2940
                      category: 'diary'
                      date: '2024-07-26'
                example2:
                  summary: '친구 관련 알림'
                  value:
                    - id: 297
                      content: 'someone wants to be friends with you'
                      category: 'mate'
                      date: '2024-07-26'
        '401':
          description: Access token이 유효하지 않거나 만료됨
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'The access token is invalid or expired'
        '404':
          description: 읽은 알림 없음
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is no unread notification'
        '500':
          description: 내부 서버 에러
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/Message'
                example:
                  message: 'There is something wrong with the server'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Message:
      type: object
      properties:
        message:
          type: string
          example: 'The link is valid'

    SignUpBody:
      type: object
      properties:
        serviceProvider:
          type: string
          example: 'Google'
        authorizationCode:
          type: string
          example: 'example code'

    Nickname:
      type: object
      properties:
        nickname:
          type: string
          example: 'musseuk'

    AccessToken:
      type: object
      properties:
        accessToken:
          type: string
          example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c'

    RefreshToken:
      type: object
      properties:
        refreshToken:
          type: string
          example: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c'

    UserInfo:
      type: object
      properties:
        id:
          type: integer
          example: 58
        profileImgURL:
          type: string
          example: 'S3 bucket image url'
        profileBackgroundImgURL:
          type: string
          example: 'S3 bucket image url'
        nickname:
          type: string
          example: 'musseuk'
        emailAddress:
          type: string
          example: 'musseuk@example.com'
        mateCount:
          type: integer
          example: 15
        diaryCount:
          type: integer
          example: 27

    MateInfo:
      type: object
      properties:
        id:
          type: integer
          example: 3798
        nickname:
          type: string
          example: 'loopy'
        profileImgURL:
          type: string
          example: 'S3 bucket image url'

    ImgURL:
      type: object
      properties:
        URL:
          type: string
          example: 'S3 bucket image url'

  parameters:
    MateID:
      name: mateID
      in: path
      required: true
      schema:
        type: integer
        example: 2764

    UserNickname:
      name: nickname
      in: query
      schema:
        type: string
        example: 'musseuk'

    UserEmail:
      name: email
      in: query
      schema:
        type: string
        example: 'musseuk@example.com'
